parameters:
  event_store_database_host: localhost
  event_store_database_port: 5432
  event_store_database_name: event_database
  event_store_database_user: user
  event_store_database_password: password
  mongodb_projection_host: localhost
  mongodb_projection_port: 27017
  mongodb_projection_authentication_database: admin
  mongodb_projection_database_name: projection
  mongodb_projection_username: user
  mongodb_projection_password: password
  mongodb_reaction_host: localhost
  mongodb_reaction_port: 27017
  mongodb_reaction_authentication_database: admin
  mongodb_reaction_database_name: reaction
  mongodb_reaction_username: user
  mongodb_reaction_password: password
  session_tokens_expire_after_seconds: 7200
