parameters:
  event_store_database_host: '%env(EVENT_STORE_HOST)%'
  event_store_database_port: '%env(EVENT_STORE_PORT)%'
  event_store_database_name: '%env(EVENT_STORE_DATABASE_NAME)%'
  event_store_database_user: '%env(EVENT_STORE_USER)%'
  event_store_database_password: '%env(EVENT_STORE_PASSWORD)%'
  mongodb_projection_host: '%env(MONGODB_PROJECTION_HOST)%'
  mongodb_projection_port: '%env(MONGODB_PROJECTION_PORT)%'
  mongodb_projection_authentication_database: '%env(MONGODB_PROJECTION_AUTHENTICATION_DATABASE)%'
  mongodb_projection_database_name: '%env(MONGODB_PROJECTION_DATABASE_NAME)%'
  mongodb_projection_username: '%env(MONGODB_PROJECTION_DATABASE_USERNAME)%'
  mongodb_projection_password: '%env(MONGODB_PROJECTION_DATABASE_PASSWORD)%'
  mongodb_reaction_host: '%env(MONGODB_REACTION_HOST)%'
  mongodb_reaction_port: '%env(MONGODB_REACTION_PORT)%'
  mongodb_reaction_authentication_database: '%env(MONGODB_REACTION_AUTHENTICATION_DATABASE)%'
  mongodb_reaction_database_name: '%env(MONGODB_REACTION_DATABASE_NAME)%'
  mongodb_reaction_username: '%env(MONGODB_REACTION_DATABASE_USERNAME)%'
  mongodb_reaction_password: '%env(MONGODB_REACTION_DATABASE_PASSWORD)%'
  session_tokens_expire_after_seconds: '%env(SESSION_TOKENS_EXPIRE_AFTER_SECONDS)%'
